//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightNovelSnifferCore_CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LightNovelSnifferCore_CLI_Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LightNovelSnifferCore_CLI_Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LightNovelSniffer_CLI.Core.Resources.LightNovelSnifferCore-CLI_Strings", typeof(LightNovelSnifferCore_CLI_Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to add another version for this LN ?.
        /// </summary>
        public static string AskAddAnotherLnVersion {
            get {
                return ResourceManager.GetString("AskAddAnotherLnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cover picture URL :.
        /// </summary>
        public static string AskCoverUrl {
            get {
                return ResourceManager.GetString("AskCoverUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authors (comma separated) :.
        /// </summary>
        public static string AskCsvAuthor {
            get {
                return ResourceManager.GetString("AskCsvAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At which chapter do you want to start (if empty, 1) :.
        /// </summary>
        public static string AskFirstChapterNumber {
            get {
                return ResourceManager.GetString("AskFirstChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At which chapter do you want to stop (if empty, until last parution) : .
        /// </summary>
        public static string AskLastChapterNumber {
            get {
                return ResourceManager.GetString("AskLastChapterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LN name (empty to stop) :.
        /// </summary>
        public static string AskLnName_EmptyToStop {
            get {
                return ResourceManager.GetString("AskLnName_EmptyToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No URL specified for {0} in this language. Please enter any chapter URL here :.
        /// </summary>
        public static string AskLnUrl {
            get {
                return ResourceManager.GetString("AskLnUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter any chapter URL here :.
        /// </summary>
        public static string AskLnVersionChapterUrl {
            get {
                return ResourceManager.GetString("AskLnVersionChapterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is the language of this version (FR/EN/...) :.
        /// </summary>
        public static string AskLnVersionLanguage {
            get {
                return ResourceManager.GetString("AskLnVersionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please, enter the root folder path to use : .
        /// </summary>
        public static string AskOutputFolder {
            get {
                return ResourceManager.GetString("AskOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use output folder &quot;{0}&quot; ?.
        /// </summary>
        public static string AskOutputFolderConfirmation {
            get {
                return ResourceManager.GetString("AskOutputFolderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à n.
        /// </summary>
        public static string AskQuestionChoicesNegativeAnswer {
            get {
                return ResourceManager.GetString("AskQuestionChoicesNegativeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à y.
        /// </summary>
        public static string AskQuestionChoicesPositiveAnswer {
            get {
                return ResourceManager.GetString("AskQuestionChoicesPositiveAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to retrieve {0} ?.
        /// </summary>
        public static string AskRetrieveLn {
            get {
                return ResourceManager.GetString("AskRetrieveLn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to retrieve the {0} version ?.
        /// </summary>
        public static string AskRetrieveLnLanguage {
            get {
                return ResourceManager.GetString("AskRetrieveLnLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of processing predefined LN. Do you want to process another ?.
        /// </summary>
        public static string LogEndOfLnInConfig {
            get {
                return ResourceManager.GetString("LogEndOfLnInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No URL for the {0} version. Process stoped..
        /// </summary>
        public static string LogNoLnUrlStopProcess {
            get {
                return ResourceManager.GetString("LogNoLnUrlStopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No URL or language for this version. Unable to add it..
        /// </summary>
        public static string LogNoUrlOrLanguageForThisVersion {
            get {
                return ResourceManager.GetString("LogNoUrlOrLanguageForThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of the program..
        /// </summary>
        public static string LogProgramEnd {
            get {
                return ResourceManager.GetString("LogProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beginning of the program..
        /// </summary>
        public static string LogProgramStart {
            get {
                return ResourceManager.GetString("LogProgramStart", resourceCulture);
            }
        }
    }
}
